### ISSUE TITLE
Linspace plot won't show up on Windows

### ISSUE THREAD

**Issue by allemand-instable** [MathInspector/MathInspector#10]
Hello,
Just installed the altest version and it seems like linspace won't show up on windows after following the tutorial on your youtube channel.
a window is created but there is no output

here's what I tried :

![qfS3Zxfy9r](https://user-images.githubusercontent.com/68656923/107033129-260c1680-67b5-11eb-9353-e0a784548e06.png)

![MathInspector_UK9SiwxA4D](https://user-images.githubusercontent.com/68656923/107033135-29070700-67b5-11eb-9156-985ed8a7c0c2.png)

thank you

===
python version : 3.9.1
===

**Comment by MathInspector** [comment]
Hmm, I just tried this exact configuration of items connected as in your screenshot, on windows 10/python 3.9.1 and it works for me.  Were there any error messages in the command prompt?  Sometimes when the plot fails it will put error messages there.

This blank window indicates that pygame is at least partially working, and it's possible there is an issue in the math inspector code, it's also possible there is a dependency problem.  One suggestion I have to help debugging is: start putting print statements (or using breakpoints) in plot2d.py in the plot function after `pygame.init()` (line 88, see here: https://github.com/MathInspector/MathInspector/blob/master/mathinspector/plot/plot2d.py#L88)

The window is opening from the .init() call, so something after that is likely causing this problem.

Have you been able to see any plot's at all, or is it always just a blank white window?

**Comment by MathInspector** [comment]
I am going to close this issue for the sake of keeping the issues section well organized.  Please feel free to additional issues, or to reopen this one if the issues listed here persist.  Cheers =)

**Comment by MathInspector** [comment]
There is a new version of math inspector (0.9.3) which has been released, and I believe it is very likely this issue has been resolved in the latest version.

Please let me know if that is not the case and I will reopen this
