### ISSUE TITLE
 Problems with indent

### ISSUE THREAD

**Issue by lcy19991113** [MathInspector/MathInspector#13]
I downloaded the windows version of MathInspector， But when I press tab, what is displayed is not an indentation length. The command line keeps prompting me: "syntaxSyntaxError: invalid syntax"

**Comment by MathInspector** [comment]
Can you please be more specific about what steps to take to reproduce this issue?

I tried opening the app on windows and pressing tab, and it worked.  However, I discovered when I press type "." and then press tab, there is a syntax error.

The tab key is used for auto-complete, as well as indentation.  This is almost certainly the source of the issue you are having.  I am not sure if resolving the bug I found will fix your issue unless I am able to reproduce what you did.

Had you typed anything before pressing tab, or was this in a code block?

**Comment by lcy19991113** [comment]
Thank you very much for your answers, I opened the software today and found that there is no error in the indent
