### ISSUE TITLE
有没有教学视频

### ISSUE THREAD

**Issue by AagsAags** [MathInspector/MathInspector#16]
有没有教学视频

**Comment by MathInspector** [comment]
是的，这里是链接，希望对您有所帮助
https://www.youtube.com/watch?v=M7U8dgPo0Bw
https://www.youtube.com/watch?v=hUHiihuOt2A

**Comment by AagsAags** [comment]
youtube视频打不开，笑哭，这是硬伤





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MathInspector/MathInspector"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月13日(星期六) 晚上10:53
收件人:&nbsp;"MathInspector/MathInspector"<MathInspector@noreply.github.com&gt;;
抄送:&nbsp;"946175224"<946175224@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MathInspector/MathInspector] 有没有教学视频 (#16)





 
是的，这里是链接，希望对您有所帮助
 https://www.youtube.com/watch?v=M7U8dgPo0Bw
 https://www.youtube.com/watch?v=hUHiihuOt2A

**Comment by MathInspector** [comment]
哦真的吗？ 那真不幸。 您可以尝试将用户手册复制/粘贴到Google翻译中，这可能会有所帮助。 如果您对支持中文用户的最佳方法有任何建议，请告诉我
https://github.com/MathInspector/MathInspector/blob/master/mathinspector/doc/manual.py

**Comment by MathInspector** [comment]
我将关闭此问题以使事情井井有条。感谢您将此问题引起我的注意。全面支持中国用户对我来说非常重要。我将研究如何在应用程序中获得尽可能多的文本翻译成中文。如果您有任何建议，请告诉我。
