### ISSUE TITLE
MathInspector won't launch and made my Mac reboot

### ISSUE THREAD

**Issue by ademenet** [MathInspector/MathInspector#17]
Hello,

First of all, thank you very much for the hard work to bring this incredible piece of software to the world!

I downloaded the package for Mac OS from the website (version 0.9.1 beta) but I haven't been able to launch the application since it just reboot my session on launch...

I am running on **Mac OS Mojave 10.14.6**. Any idea where it could come from?

Thank you.

**Comment by MathInspector** [comment]
Yes, sorry about that!  Thanks for reporting this and helping to test!  I had been working on a fix for this issue, and got distracted by adding more features.  This issue is really complicated and hard for me to reproduce, which is why it's taking so long to fix.
