### ISSUE TITLE
Broken copy function in mathinspector shell (concatenates copied text to the clipboard instead of replacing it)

### ISSUE THREAD

**Issue by EtienneDesticourt** [MathInspector/MathInspector#26]
Hiya,

The copy function in the mathinspector shell concatenates copied text instead of replacing it.

**How to replicate:**
* Launch mathinspector
* Select the first few lines in the shell 
```
Math Inspector UNKNOWN (Beta)
Type "help", "copyright", "credits", "license" for more information
```
* Right-click
* Click copy
* Right-click
* Click copy
* Paste the text somewhere
* The text is pasted twice.
```
Math Inspector UNKNOWN (Beta)
Type "help", "copyright", "credits", "license" for more information
Math Inspector UNKNOWN (Beta)
Type "help", "copyright", "credits", "license" for more information
```

Additionally some kind of internal clipboard must be used because if you copy something else outside the application, then right-click->Copy again inside the application the contents of the clipboard will still contain the content that was copied before the outside-copy.

Thank you for all your work on this application.

**Comment by MathInspector** [comment]
> some kind of internal clipboard must be used

It's using the tkinter clipboard but the implementation has a bug.  I have seen this error before and have been meaning to fix this.  There are also a few quality of life things related to copy/paste I have been meaning to take care of so hopefully before anyone else notices those things I will have them fixed already ;-)

There should hopefully be a new release 0.9.4 out this week with fixes for this an other issues.  Thanks for helping to test!
