### ISSUE TITLE
Storing the output of a function node into a numpy array variable sometimes sets the array shape to the function output instead of the array value

### ISSUE THREAD

**Issue by EtienneDesticourt** [MathInspector/MathInspector#29]
Hi,

It's a bit of a complicated one to replicate.

In the mathinspector console type:
```
import numpy as np
x = np.array([1, 2, 3])
def f(x):
    return x*2
c = 0
```

In the node editor:
* link x to the input of f
* link the output of f to c

In the mathinspector console type:
`c = f(x)`

In the node editor:
* Link the output of f to c

`c` should take the value `[2, 4, 6]` but instead it takes the shape `(2, 4, 6)` and is filled with a bunch of values close to 0 and NaNs. I'm thinking some memory that shouldn't be read is being read.

Thank you.

**Comment by MathInspector** [comment]
> c should take the value [2, 4, 6] but instead it takes the shape (2, 4, 6)

Interesting!  On my mac this is working properly, it may be a linux specific issue.

> link the output of f to c  

Was the output of `f` connected to `c`?  If so, that is a bug.  This is a very tricky subject, the problem is that if the output is connected on assignment calls like in the example `c=f(x)`, then it will result in code which runs in mathinspector to execute differently than a normal python environment.

To see this, consider what would happen if you ran
```python
x = 2
c = f(x)
f(11)
d = c
```

In a normal python environment, `d` will have the value of `f(2)`.  A requirement of mathinspector is that everything has to be the same as a normal python environment, this is why I removed assignment triggered wire connections like that, and why if this is happening it's a bug.

**Comment by MathInspector** [comment]
I was able to reproduce this, nice catch!!  I think I know what is going on.

P.S. I had previously misread the instructions to reproduce the error, and deleted my prior response

P.P.S. Thank you so much for taking the time to report these.

**Comment by EtienneDesticourt** [comment]
Ah ok nice, I was working on recording my screen but it's not so easy on linux :p !

In response to your previous answer, though, it made me realize the current behaviour of function calls in the console and node editor does not make sense to me.
In my opinion, functions should have as many nodes as the number of calls (with the exception of looped-calls), not a single node with an inner parameter that gets updated to the latest call. Otherwise what's the point of a function?

A similar example to the one you'd written:

```
x = 1
y = 2

def f(x):
   return x*2

c = f(x)
d = f(y)
e = f(3)
f(4)
```

What's the correct node-editor state in this case?
To me it's 3 `f` nodes (let's call them `f1`, `f2`, `f3` for this example but they'd all appear as `f`).
As well as one `x` node, one `y` node, one `constant` node set to `3` respectively connected to the inputs of `f1`, `f2`, `f3`.
And three outputs nodes `c`, `d`, `e` at the output of respectively `f1`, `f2`, `f3`.
And no nodes for the 4th call of f since nothing is stored.

**Comment by MathInspector** [comment]
> In my opinion, functions should have as many nodes as the number of calls

In my own words, I call this feature "having multiple outgoing wires for each item in the workspace"

> In response to your previous answer, though, it made me realize the current behaviour of function calls in the console and node editor does not make sense to me.

You are so right!  This is a feature I have been planning for awhile, and it makes me really happy to see that you picked this up =)  The reason a multiple outgoing wires feature makes so much sense is because it reflects visually what is going on in the underlying python interpreter.  

That is exactly the vision I am going for, so if you notice anything else like that, please point it out even if you are not 100% sure.

I had previously implemented a multiple outgoing wires feature but its a big job.  I consider it a new feature and not a bug, but its becoming very important for my own purposes since I need this feature to support animations and a few other things I really need on a practical level for my own video production work.  I am going to try and get this feature into this push of bug fixes.

**Comment by EtienneDesticourt** [comment]
Awesome, happy to hear that it's in the work! I'd really recommend you go with a multi-node implementation rather than a multi-wire one though for the following reasons:
* It keeps the number of input/output parameters clear. (2 wires in-> two input parameters)
* It allows the user to group nodes geographically based on their usage
* It stays legible for a high number of function calls
* It's the standard visual language that people have come to expect of visual programming tools (unreal engine, matlab, etc...)

**Comment by MathInspector** [comment]
> I'd really recommend you go with a multi-node implementation rather than a multi-wire one

Interesting!  I am considering this now.

Question:  When you say "multi-node implementation", does "node" refer to an item in the node editor, or number of output nodes associated with a single item?  How would you suggest dealing with a situation where a user wants to drag 10 outgoing wires from a single item, should there be 10 items?  I think if there were 10 items, things would get cluttered really fast, so perhaps I am misunderstanding the suggestion.  I thought the best UI would be to have a single output node and allow multiple outgoing wires.

> It's the standard visual language that people have come to expect of visual programming tools

I am a big blender user, and below I have posted a screenshot from blender cycles (which was the main inspiration).  I also like unreal engine a lot, and have posted a screenshot from that with multiple outgoing wires.

That being said, I want mathinspector to strongly conform to the industry standards for visual node editor environments of the unreal engine type.

I felt there was a really strong case for multiple outgoing wires, and now I am questioning this.  Can you please explain in a little more detail what you think the ideal UI is for the use case you have in mind.  I want to make sure I clearly understand what you are getting at.

<img width="381" alt="Screen Shot 2021-02-23 at 8 52 40 AM" src="https://user-images.githubusercontent.com/60369559/108853314-92a85300-75b4-11eb-99ff-0e16c7bd18b6.png">

![unrealstudio3_img13_jfxs0q](https://user-images.githubusercontent.com/60369559/108853823-2b3ed300-75b5-11eb-9a32-159c3f150c3e.jpg)

**Comment by EtienneDesticourt** [comment]
Ah sorry, I misunderstood what you were suggesting, and I also completely forgot the case of iterables and tuples.

When I said multi-node I meant that a single python object could appear multiple times in the node editor as different nodes/items, so like in the unreal engine behaviour `Set Value Target with Blend` is a single function which appears four times,  once for every call. I haven't used blender enough to compare.

When you said multi-wire I thought you meant one node/item per function. And to that node are connected as many  in/out wires as there are calls. So for example if  you call f(x) and f(y), f being a function with one input argument, and x, y being integers, I thought you meant we'd have one f node/item in the node-editor with wires coming from x and y and going into the single f node/item. But I see now that's not what you meant.

I haven't thought about how the node-editor should behave for lists/vectors/tuples, so I have no strong opinion on it as of now. Maybe multiple wires for tuples, and a single wire for other Iterables which could be coupled with unpacking functions.

So I think we're on the same page, we just got our wires crossed :D

**Comment by MathInspector** [comment]
> So I think we're on the same page, we just got our wires crossed :D

LOL!!! I detect a pun.

This discussion has been extremely productive imo, I feel like we just solved a problem I have been worrying about for months regarding *args and at the same time also solved the problem of how to implement multiple output nodes to be more like blender cycles.

**Comment by MathInspector** [comment]
> When I said multi-node I meant that a single python object could appear multiple times in the node editor

Having used mathinspector to write mathinspector for some time now, I can tell you there is a problem UX wise when it comes to large projects.  The number of items in the node editor can quickly become overwhelming.  

I am very hesitant to automatically create multiple items per single object.  This would destroy the symmetry of the representation where each item in the node editor corresponds to an object in the local namespace of the interpreter.  Dealing with multiple items in the node editor with the same name would also increase the confusion level for a number of use cases imo.  If you feel strongly about this, I'd really like to know more because if I can understand the use case here better, then I will be able to see how to solve it better as well.

**Comment by casperdcl** [comment]
let's say you have this:

```
a -> b -> c
|
V
d -> b -> e
```

Even though function `b` is the same (python object), it's easier to see the flow of data by writing it twice in two separate branches.

Yes, in general I think it's best to keep a one-to-one correspondence between number of nodes and number of python objects, but I think there has to be an option to enable "alias" nodes... maybe right-click on a node and say "create visual copy" purely for the purpose of flowcharts (not actually creating a new python object).

**Comment by MathInspector** [comment]
> I think there has to be an option to enable "alias" nodes

here is how i currently do this
```python
def f(x):
    return x + 1

f2 = f
```

> maybe right-click on a node and say "create visual copy" purely for the purpose of flowcharts

this is a great suggestion!  I'm adding it to the list.  it also would be nice to have a right click menu option for "change variable name"

**Comment by EtienneDesticourt** [comment]
> let's say you have this:

Yeah exactly, and to add on top of this, this behaviour is dictated by the inputs. One thing that was getting me confused between our viewpoints is that I'm focused on inputs but @MathInspector you're focusing mostly, I think, on multiplexing outputs. And input and output wires don't need to have the same behaviour.

So in the case where you have multiple inputs, necessarily you need multiple functions:
```
a -> b -> c
|
V
d -> b -> e
```

But in a case with multiple outputs from a single input you could have multiple output wires from a single function node:
```
a -> b -> c
       |
      V
      d
```

**Comment by MathInspector** [comment]
> But in a case with multiple outputs from a single input you could have multiple output wires from a single function node:

Yup.  For example

```python
t = 1
def f(a,b,c):
    return a + b + c
f(t,t,t)
```
will result in 2 items being created in the node editor, and the `t` item having 3 outgoing wires from a single output node into the 3 inputs of the item for `f`

> One thing that was getting me confused between our viewpoints is that I'm focused on inputs but @MathInspector you're focusing mostly, I think, on multiplexing outputs

This kind of information and feedback is extremely useful to know.  A big part of my focus on UI/UX is to *anticipate* the assumptions people are making about the way the UI is "supposed" to work.

**Comment by MathInspector** [comment]
I have reread our discussion and this is my final comment before going offline for at least a few hours to get coding.

 > so like in the unreal engine behaviour Set Value Target with Blend is a single function which appears four times, once for every call

I think I understand what you were saying this whole time after a reread, and this comment really stuck out to me.  There is a distinction between unreal engine and mathinspector in that mathinspector needs to support the entire python programming language, and there is a "fork in the road" when it comes to visual node editor design.  The two paths are

- the visualization represents the memory of the running program
- the visualization represents the abstract syntax tree that the interpreter produces as it processes command strings

For this reason, imo it's justified to not follow the unreal engine pattern of having an item in the node editor corresponding to the number of times the function is called.

Instead, for mathinspector it would be preferable to have the visual representation for recursive function calls work in a way that actually does not conform to the industry standard.  In cases like this, the roadmap I have is to closely investigate and emulate the internals of how python works under the hood, and then to combine that with whatever makes my life the easiest when I am doing stuff in the node editor.

**Comment by MathInspector** [comment]
The options for creating a copy and renaming items are in the current PR
<img width="685" alt="Screen Shot 2021-02-25 at 6 22 17 PM" src="https://user-images.githubusercontent.com/60369559/109233338-b1b30a80-7797-11eb-952e-fcaccb06eea9.png">
