### ISSUE TITLE
shorter import error/warning message

### ISSUE THREAD

**Issue by casperdcl** [MathInspector/MathInspector#30]
When loading `autosave.math` after `pip uninstall`ing previously imported packages, the error message could be more concise (one line per failed import)

From https://github.com/MathInspector/MathInspector/issues/25#issuecomment-784244813

**Comment by MathInspector** [comment]
<img width="819" alt="Screen Shot 2021-02-23 at 2 51 18 PM" src="https://user-images.githubusercontent.com/60369559/108899649-a8cf0700-75e6-11eb-918a-03c397741d20.png">

I am happy with the way this came out.  It's so much better
