### ISSUE TITLE
Left-Click doesn't close context menus

### ISSUE THREAD

**Issue by EtienneDesticourt** [MathInspector/MathInspector#32]
Hi,

Context menus open by right-clicking in any part of the window (sidebar, node-editor, console) cannot be closed by left-clicking outside the menu or pressing the escape key. One of the menu item has to be clicked to close the menu.

Possible solution:
https://mail.python.org/pipermail/python-list/2002-September/161459.html

Cheers

**Comment by MathInspector** [comment]
FocusOut does not seem to be a very reliable event.

I added `menu.unpost()` to the left click and escape keys for the node editor which should resolve this one.

**Comment by EtienneDesticourt** [comment]
Having installed the PR, the problem is fixed for the node-editor context menu but remains for the sidebar as well as the console.

**Comment by MathInspector** [comment]
Gotcha, I should have realized that!  

I just pushed a fix which should make left clicking close the menu across the entire app.  If you pull the latest from dev, it should work now
