### ISSUE TITLE
Can't click on the commands in the context menu of the node-editor

### ISSUE THREAD

**Issue by EtienneDesticourt** [MathInspector/MathInspector#34]
Hi,

I'm on linux, using the master version.
The cascades work (though they don't unroll on hover unlike their menubar counterparts for some reason) but you can't click on the commands in the context menu of the node-editor.

They start working if you replace this line: https://github.com/MathInspector/MathInspector/blob/23c66f0f4b4684f67b1bd5999063904f2dd5755f/mathinspector/widget/menu.py#L39
with `menu = Menu(self)`

Cheers

**Comment by MathInspector** [comment]
Oh nice!   I made this change and everything seems to be working fine, so I don't think it broke anything, only fixed something.
