### ISSUE TITLE
View source button doesn't work on linux

### ISSUE THREAD

**Issue by EtienneDesticourt** [MathInspector/MathInspector#35]
Hi,

This line is the culprit:
https://github.com/MathInspector/MathInspector/blob/23c66f0f4b4684f67b1bd5999063904f2dd5755f/mathinspector/util/common.py#L54

There is no start command to my knowledge on Linux. I'd suggest checking the $EDITOR environment variable instead.

Cheers

**Comment by MathInspector** [comment]
<img width="458" alt="Screen Shot 2021-02-23 at 10 21 29 PM" src="https://user-images.githubusercontent.com/60369559/108942732-86a8a980-7625-11eb-9d60-ff053ecf8fa7.png">

I think this should do it, have not had a chance to test on linux yet tho.  (the dev branch on my local has fixes for almost all the things we discussed today btw)

**Comment by MathInspector** [comment]
I thought you might like to join the mathinspector discord, here is a one time use link that expires in 6 hours
https://discord.gg/dRpKN24

At the moment its just myself, casper.dcl, and one other person.

P.S. The previous solution had a bug, but it has been fixed now and I tested this on linux

```python
    elif platform.system() == "Linux":
        editor = os.environ["EDITOR"] if "EDITOR" in os.environ else "vi"
        command = editor + " " + file
```

**Comment by MathInspector** [comment]
I was wondering about using `&` to launch vim in the background.  It was causing some strange issue.  e.g.

```python
os.system("vi file.py &")
```

do you know if i was doing that wrong, or is there a better way to run vi in the background?

**Comment by EtienneDesticourt** [comment]
Use the subprocess module and start the process so it doesn't wait for it to exit

**Comment by MathInspector** [comment]
> Also ideally it'd be good to test if $EDITOR is set and popup an error or something if it isn't.

I have it doing this at the moment, but error popup is probably better
```python
editor = os.environ["EDITOR"] if "EDITOR" in os.environ else "vi"
```

**Comment by EtienneDesticourt** [comment]
I think git does it your way so it's probably a good way and pretty hassle free

**Comment by MathInspector** [comment]
The positive aspect of showing an error message is it enforces best practices on the user.  This kind of goal for a UI design pattern is something I want to explore more and see if there are opportunities to change the UI in places with this idea in mind.
