### ISSUE TITLE
macOS download contains version 0.0.0 

### ISSUE THREAD

**Issue by suschizu** [MathInspector/MathInspector#8]
hello - I just wanted to report that the mac download contains a broken short version string (0.0.0 instead of 0.9.0)
(https://mathinspector.com/download/mathinspector_0.9.0.dmg)

info.plist
```
CFBundleShortVersionString:
0.0.0
```

<img width="345" alt="Screenshot 2021-02-02 at 18 24 36" src="https://user-images.githubusercontent.com/16004333/106638259-f88c5680-6583-11eb-8fe5-f469c75c6619.png">

**Comment by MathInspector** [comment]
Thanks for reporting this issue!  I am happy to report that a new version of math inspector is out, 0.9.1, which no longer has this issue

**Comment by suschizu** [comment]
thanks @MathInspector :)
