### ISSUE TITLE
tag releases

### ISSUE THREAD

**Issue by das-g** [MathInspector/MathInspector#9]
Please mark the Git revisions corresponding to a release with an appropriate Git tag, so that the exact code corresponding to a release can be determined.

**Comment by MathInspector** [comment]
Good call, thanks for the suggestion.  This is what I will do going forward.

**Comment by MathInspector** [comment]
Can you please let me know if I did this properly?  https://github.com/MathInspector/MathInspector/tags

I retroactively added a tag to the last commit, and if you have any more suggestions about how to keep things well organized, they are much appreciated!

**Comment by das-g** [comment]
> Can you please let me know if I did this properly? https://github.com/MathInspector/MathInspector/tags

Looks good to me. :+1:

> I retroactively added a tag to the last commit, and if you have any more suggestions about how to keep things well organized, they are much appreciated!

You could, if you want, add tags for other releases than the most recent one, too. But I guess having one for the most recent one (and any future releases once they're released) is what was needed most, so I'll close this issue now.
